### ISSUE TITLE
Design SSK -  resources not clickable

### ISSUE THREAD

**Issue by dseillier** [ParthenosWP4/SSK#17]
When we jump of steps, sometimes the resources below is not accessible anymore. We need to refresh the page.

**Comment by dseillier** [comment]
<img width="360" alt="capture d ecran 2018-04-05 a 11 30 15" src="https://user-images.githubusercontent.com/17833827/38358156-cd57e1bc-38c4-11e8-9de8-a79d6c8206df.png">

**Comment by charlesriondet** [comment]
This is fixed, right?

**Comment by dseillier** [comment]
I hope so
