### ISSUE TITLE
Steps with no resources ?

### ISSUE THREAD

**Issue by dseillier** [ParthenosWP4/SSK#31]
It is always awkward to read a step with no resource at all. 

Should the step be erased / mixed with another ? Should we add something minimum ?

**Comment by charlesriondet** [comment]
We could either add a generic text saying "There is no resources for this step" or similar or require that at least a resource is provided.
I prefer the first, because nothing is better than a irrelevant resource.

**Comment by dseillier** [comment]
I dont get it : what do you prefer ? Stating that there is nothing (when its the case) or "faking" a resource to fill an empty space ?

**Comment by charlesriondet** [comment]
The first = `add a generic text saying "There is no resources for this step" or similar`

**Comment by charlesriondet** [comment]
New design of steps fix this issue.
