### ISSUE TITLE
Content not loaded in non-ssl website

### ISSUE THREAD

**Issue by KlausIllmayer** [ParthenosWP4/SSK#32]
If going to the SSK website with a non-ssl link, e.g. http://ssk-application.parthenos.d4science.org/ssk/#/scenarios the website is shown but there is no content, because of a missing CORS setting > either change the CORS rules or redirect to the ssl-version

**Comment by charlesriondet** [comment]
Closing this as we changed server: http://ssk.huma-num.fr
