### ISSUE TITLE
Thumbnails are not always created correctly

### ISSUE THREAD

**Issue by KlausIllmayer** [ParthenosWP4/SSK#37]
Have a look here: https://ssk-application.parthenos.d4science.org/ssk/#/scenarios/AWIAie9fe-S72mFoMfca/1
The general resources item "Open Data in a Big World" is a pdf, I guess that is the reason why the thumbnail is not rendered correctly (it seems to be a screenshot of a 404 webserver error). Strangely it is also not working for the Project specific resource "The Value of Open Data Sharing"

**Comment by charlesriondet** [comment]
Lionel dismissed this feature and now only display `fake`thumbnails.
