### ISSUE TITLE
"Spec" and "Specification"

### ISSUE THREAD

**Issue by mpuren** [ParthenosWP4/SSK#7]
In the Heritage Sciences scenarios, words "spectra" and "spectrum" have transformed into "specificationtra" and "specificationtrum". 

For instance, in the TEI file ((step_AS_081117.xml):
<head xml:lang="en">Analyzing the spectra</head>
On the website: "Analyzing the specificationtra"

**Comment by Statali** [comment]
Thanks for the remark. 
you can test if it's ok, because I have solve the issue.

**Comment by mpuren** [comment]
It doesn't work... Still the same problem on the website: "Raman specificationtrometry" instead of "Raman spectrometry", or "Multispecificationtral imaging" instead of "Multispecificationtral imaging"...etc.
I don't know if it can help you: I've noted that, if I use a capital letter at the beginning of the word ("Spectrum" instead of "spectrum"), there is no problem.

**Comment by Statali** [comment]
This is what I have on the current version after last updating about you issue.
<img width="1378" alt="capture d ecran 2017-11-10 a 10 01 32" src="https://user-images.githubusercontent.com/17985571/32650548-81f20722-c5fe-11e7-9e9b-e43266810bda.png">

**Comment by mpuren** [comment]
Ah yes! It works! Thanks Lionel!

**Comment by Statali** [comment]
Your are welcome, but still some issues in step content that I'm trying to solve.

**Comment by mpuren** [comment]
Ok noted

**Comment by Statali** [comment]
En fait Marie, ce fichier step_RRS_081117.xml n'est pas bien formé.

**Comment by mpuren** [comment]
C'est corrigé!

**Comment by mpuren** [comment]
Je vais vérifier les autres
